import 'package:flutter/foundation.dart';

class Employee {
  final int employeeId;
  final String firstName;
  final String lastName;
  final String email;
  final String? phoneNumber;
  final String? role;
  final DateTime? hireDate;

  Employee({
    required this.employeeId,
    required this.firstName,
    required this.lastName,
    required this.email,
    this.phoneNumber,
    this.role,
    this.hireDate,
  });

  factory Employee.fromJson(Map<String, dynamic> json) {
    return Employee(
      employeeId: json['employee_id'] as int,
      firstName: json['first_name'] as String,
      lastName: json['last_name'] as String,
      email: json['email'] as String,
      phoneNumber: json['phone_number'] as String?,
      role: json['role'] as String?,
      hireDate: json['hire_date'] == null
          ? null
          : DateTime.parse(json['hire_date'] as String),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      // employee_id is not included as it is auto-generated by the database
      'first_name': firstName,
      'last_name': lastName,
      'email': email,
      'phone_number': phoneNumber,
      'role': role,
      'hire_date': hireDate?.toIso8601String(),
    };
  }

  Employee copyWith({
    int? employeeId,
    String? firstName,
    String? lastName,
    String? email,
    ValueGetter<String?>? phoneNumber,
    ValueGetter<String?>? role,
    ValueGetter<DateTime?>? hireDate,
  }) {
    return Employee(
      employeeId: employeeId ?? this.employeeId,
      firstName: firstName ?? this.firstName,
      lastName: lastName ?? this.lastName,
      email: email ?? this.email,
      phoneNumber: phoneNumber != null ? phoneNumber() : this.phoneNumber,
      role: role != null ? role() : this.role,
      hireDate: hireDate != null ? hireDate() : this.hireDate,
    );
  }
}
